version: "3.9"

services:
  postgres:
    image: postgres:16
    # Alfred for allowing more workers
    # TODO load custom postgresql.conf or change inside container when creating: work_mem = 6GB, maintenance_work_mem = 6GB
    privileged: true
    #user: postgres
    restart: always
    shm_size: 4g
    command: postgres #--config-file=/var/lib/pgsql/data/postgresql.conf #/usr/lib/postgresql/16/bin/postgres
    ports:
      - 5433:5432
    # TODO also expose unix socket for direct local connection
    deploy:
      placement:
        constraints:
          - node.hostname==r73043420
#          - node.labels.database == true # only deploy on nodes with label database=true
    volumes:
      # create folder first, and may need to change permissions afterwards for saving with dvc
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Cc17931793
      - POSTGRES_USER=alfred
      - POSTGRES_DB=cs234_db
#    env_file:
#      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 30s
      retries: 3